#!/bin/bash
#baxter
./baxter.sh sim #for every window
roslaunch baxter_gazebo baxter_world.launch
rosrun baxter_interface joint_trajectory_action_server.py
roslaunch baxter_moveit_config demo_baxter.launch
rosrun baxter_tools enable_robot.py -e
python move_arm.py --robot=baxter
#moveit
roslaunch panda_moveit_config demo.launch rviz_tutorial:=true 
python move_arm.py --robot=panda_arm